version: '3'
services:
  elasticsearch:
    image: "elasticsearch:7.4.2"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - elastic_network

  kibana:
    image: "kibana:7.4.2"
    ports:
      - "5601:5601"
    depends_on: 
      - "elasticsearch"
    networks:
      - elastic_network

networks:
  elastic_network:
