# Use root/example as user/password credentials
version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: example
    ports:
      - 5672:5672
      - 15672:15672

