# Use postgres/example user/password credentials
version: '3.1'

services:

    db:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      ports:
        - 5432:5432

    adminer:
      image: adminer:latest
      restart: always
      ports:
        - 8888:8080
